version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: lomus
      POSTGRES_USER: lomus_user
      POSTGRES_PASSWORD: lomus_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
